# Subtract the first heading from all msgs so that the origin is in zero (OpenVINS sometimes starts rotated by pi/2)
init_in_zero: true

# Wait for a service call that calibrates the level horizon (zero roll and pitch)
# VINS algorithms initialize during initial motion, so the origin can be not gravity-aligned
compensate_initial_tilt: false

rate_limiter:
  enabled: true
  max_rate: 100.0 # [Hz]
